[project]
name = "nanogpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.2",
    "tensorboard>=2.20.0",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
]

[tool.ruff]
line-length = 88
select = ["E", "F", "I"] # 检查错误、格式、导入顺序

[tool.ruff.isort]
known-first-party = ["src"]

[dependency-groups]
dev = [
    "ruff>=0.15.5",
]
